### ISSUE TITLE
Cart won't restore when order has been canceled

### ISSUE THREAD

**Issue by stefanfr** [paynl/magento-plugin#24]
Quote isn't saved properly after order got canceled. Quote is still unavailable after setting it back to Active. To fix this change:
`$quote->setIsActive( true )->save();`

To:
`$quote->setIsActive( true )
                    ->setReservedOrderId(null)
                    ->save();
Mage::getSingleton('checkout/session')->replaceQuote($quote);`

**Comment by andypieters** [comment]
Thanks!
I've added this fix to the latest release (v3.12.11)
