### ISSUE TITLE
Error by install new version pay.nl for Magento 1.9

### ISSUE THREAD

**Issue by yohha** [paynl/magento-plugin#25]
Parse error: syntax error, unexpected '(' in /home/fungifts/public_html/app/code/community/Pay/Payment/Model/Paymentmethod.php on line 292

![image](https://user-images.githubusercontent.com/25413710/49002876-0b639f00-f161-11e8-8aac-964b2bbc5709.png)

**Comment by andypieters** [comment]
Why are you installing version 3.8.4? its over a year old.
Please try the latest version (3.12.11)
https://github.com/paynl/magento-plugin/releases/download/v3.12.11/Pay_NL-3.12.11.tgz

**Comment by yohha** [comment]
im sorry but this is the last version on magento connect

**Comment by andypieters** [comment]
magento connect is discontinued.
For magento 1, you can only use the direct download from the link i just shared.

**Comment by yohha** [comment]
same error

  Creating backup...
Database backup has been created


CONNECT ERROR: Package file is invalid
'./app/code/community/Pay/Payment/Block/Adminhtml/Paymentmethods.php'
already exists

**Comment by yohha** [comment]
ok working perfect
only i see a new tab
[image: image.png]
what do i need to put in the Tokencode?

**Comment by yohha** [comment]
thank you very much for your help
