### ISSUE TITLE
Images on checkoutpages won't load

### ISSUE THREAD

**Issue by riccardofinkers** [paynl/magento-plugin#37]
in Pay/Payment/Block/Form/Abstract.php

Line 39:             ->setPaymentMethodImageSrc('https://www.static.pay.nl/payment_profiles/' . $iconSize . '/' . $this->paymentMethodId . '.png')

change to:
            ->setPaymentMethodImageSrc('https://static.pay.nl/payment_profiles/' . $iconSize . '/' . $this->paymentMethodId . '.png')

**Comment by IvoWams** [comment]
This will be fixed in an upcoming release. Thanks for bringing this to our attention.
