### ISSUE TITLE
Notice: Undefined offset: 1  in /app/design/frontend/base/default/template/pay/payment/form/afterpay.phtml on line 8

### ISSUE THREAD

**Issue by loekvangool** [paynl/magento-plugin#52]
in https://github.com/paynl/magento-plugin/blob/master/app/design/frontend/base/default/template/pay/payment/form/afterpay.phtml, an assumption is made about `$this->getDob();`:

```php
$dob = $this->getDob();
/** @var Mage_Sales_Model_Quote $quote */
$quote = $this->getQuote();

list($dobYear, $dobMonth, $dobDay) = explode('-', $dob);
```

Leading to `Notice: Undefined offset: 1  in [..]/app/design/frontend/base/default/template/pay/payment/form/afterpay.phtml on line 8`.

Possible solution:
```php
list($dobYear, $dobMonth, $dobDay) = array_pad(explode("-", $dob), 3, null);
```

**Comment by escruickshank** [comment]
Hi! Thank you for your comment. We have not been able to reproduce this on the latest version of our plugin (v3.16.0). If you are not on this version already, please update.
