### ISSUE TITLE
Icons bij OneStepCheckout werken niet

### ISSUE THREAD

**Issue by kayvanaarssen** [paynl/magento-plugin#6]
Hi, 
De icons werken niet bij de OneStepCheckout van: https://www.onestepcheckout.com

De optie hiervoor staat wel aan in de backend. Kan dit opgelost worden?

<img src='http://d.pr/i/NlCG+'>

<img src='http://d.pr/i/sibP+'>

**Comment by dreamhosting** [comment]
Hier hetzelfde! Wij hebben ze dmv CSS zelf toegevoegd.

<img width="299" alt="screen shot 2017-06-14 at 19 48 34" src="https://user-images.githubusercontent.com/2556424/27146689-7870aa0c-513a-11e7-98a3-a1c822969316.png">

@media all {
    label[for="p_method_pay_payment_ideal"] {
        background: url(../images/pay_logos.jpg) top left no-repeat;
        padding-left: 54px;
        height: 27px;
        line-height: 27px;
    }
}

Waar de file pay_logos.jpg alle logo's bevat.

**Comment by kayvanaarssen** [comment]
Zou fijn zijn als Pay.nl dit standaard toevoegt in hun module. Dan werkt het ook altijd zoals het hoort.
Zelfde geld inderdaad voor de toeslagen.

**Comment by andypieters** [comment]
Probleem is, dat ik niet weet waarom hij in onestepcheckout de iconen en toevoeging van de kosten niet weergeeft.
Hier wordt de html aan het label toegevoegd:
https://github.com/paynl/magento-plugin/blob/master/app/code/community/Pay/Payment/Block/Form/Abstract.php#L60

Alleen in onestepcheckout levert dit problemen op, maar ik heb geen kopie van die plugin.
Zou een van jullie die kunnen mailen naar support@pay.nl, t.a.v. Andy Pieters dan kan ik debuggen wat er precies niet goed gaat.

Met vriendelijke groet,

Andy Pieters

**Comment by kayvanaarssen** [comment]
@andypieters Ik heb je een mailtje gestuurd met de module.
Ik hoop dat je wat kunt vinden en een fix kunt maken zodat het voor iedereen werkt.

**Comment by andypieters** [comment]
Support systeem heeft de attachment helaas verwijderd :(
Zou je hem naar mijn eigen mail kunnen sturen? andy@pay.nl

**Comment by andypieters** [comment]
Helaas lukt het niet.
Ik heb allerlei manieren geprobeerd om de label te beinvloeden, maar helaas werkt het niet in combinatie met onestepcheckout.
Zelfs als ik de img in het label teruggeeft wordt dit geescaped en zie je dus niet de image maar de <img > tag.
Dus helaas, het werkt niet in combinatie met onestepcheckout, sorry
