### ISSUE TITLE
Creditfactuur mislukt: You do not have enough credit to refund this amount

### ISSUE THREAD

**Issue by joostaafjes** [paynl/magento-plugin#7]
Bij het aanmaken van een creditfactuur krijg ik de foutmelding: You do not have enough credit to refund this amount

De bijbehorende bestelling is gedaan met Focum/AchterafBetalen.

**Comment by andypieters** [comment]
Klopt, er moet voldoende saldo zijn voor een refund.
Dit is een beperking die pay.nl oplegt, heeft niet met de plugin te maken
