### ISSUE TITLE
Autoloader with observers

### ISSUE THREAD

**Issue by cstergianos** [paynl/magento-plugin#9]
Hi! I was doing a small review to your extension and I found out that you call the autoloader with 3 different events. Wouldn't be easier if you just add these packages in the vendor folder through your composer.json. Is there a plan to fix this in the future?

**Comment by andypieters** [comment]
Hi! thanks for reviewing the code.
I use the same events as:
https://github.com/magento-hackathon/Magento-PSR-0-Autoloader/blob/master/app/code/community/Hackathon/PSR0Autoloader/etc/config.xml
The autoloader only runs once, so it shouldn't be a problem.
Now that iam thinking about it, i think i stole the code from there :wink: 
The thing with magento 1 is, that it doesn't do anything with composer.json.

If you think something can be approved, let me know. or better yet, send me a pull request :smiley: 
Best regards,

Andy Pieters
